### PR TITLE
Add Dockerfile for Python script

### PR DESCRIPTION
**Pull request by luigigubello**
This PR adds a Dockerfile for the Python script `validator-and-generator.py`. This should partially solve https://github.com/ossf/security-insights-spec/issues/33

### CODE REVIEW

**Comment by luigigubello** [comment]
@eddie-knight can you try to run the script now?

**Comment by eddie-knight** [comment]
Testing this now.

Regarding the documentation update, may I recommend that we change to utilizing the GitHub vulnerability reporting tooling for this repo? (security tab at the top)

**Comment by eddie-knight** [comment]
The containerization works as intended! I didn't get very far in testing the functionality, but that can be improved in follow-up PRs if needed.
Screen Shot 2023-09-18 at 5 37 25 AM

**Review by eddie-knight — CHANGES_REQUESTED** [review]
My only request before merge is that we do the full reorganization (file-creation and file-deletion) in the same PR. Currently this will result in two copies of the python code in the main branch.

**Comment by luigigubello** [comment]
> _Currently this will result in two copies of the python code in the main branch._

Oh right, this was definitely not intended.

**Comment by luigigubello** [comment]
> _Regarding the documentation update, may I recommend that we change to utilizing the GitHub vulnerability reporting tooling for this repo? (security tab at the top)_

Yes, good point. We have the private vulnerability reporting enabled, I will also add a SECURITY.md in a different PR.

**Review by eddie-knight — APPROVED** [review]

**Pull request merged**
