### PR TITLE
Add Golang validator [DRAFT]

### PR DESCRIPTION
**Pull request by luigigubello**
Merge after https://github.com/ossf/security-insights-spec/pull/38 to avoid conflicts. This PR is still a draft.

### CODE REVIEW

**Comment by luigigubello** [comment]
Currently, this validator doesn't validate the current samples, which should be correct. cc @eddie-knight

**Comment by eddie-knight** [comment]
> doesn't validate the current samples 

Yep. The intent is to add a CI check in a follow-up PR that will validate all future changes to example files.

**Comment by eddie-knight** [comment]
@luigigubello Are you familiar with how to keep the commit history from the repo you pulled this from? 

Been a while since I've done that, and I know it's annoying. I can push an update to this branch or make a new PR if needed to preserve the commits.

**Comment by luigigubello** [comment]
> _Are you familiar with how to keep the commit history from the repo you pulled this from?_
> _Been a while since I've done that, and I know it's annoying. I can push an update to this branch or make a new PR if needed to preserve the commits._

@eddie-knight sorry for my late response 🙌 Honestly, I am unfamiliar with how to preserve the commit history in this case (I don't have forked your project), but I think you are right. In the meantime, I have added the credits in the README :) do you think we need to preserve the commit history or do you want only the acknowledgment?

**Comment by eddie-knight** [comment]
Per our slack convo, I'll be adding improvements to the output text and will push the changes soon

**Pull request closed without merging**
