### PR TITLE
Added LICENSE.md to cover spec and code

### LINKED ISSUE #41: Add spec license
Conversation with @hythloda has highlighted a need for the specification to be licensed before the first release is cut.

For reference:
- https://github.com/SBOMit/specification/blob/main/LICENSE.md
- https://github.com/ossf/s2c2f/blob/main/LICENSE.md

### PR DESCRIPTION
**Pull request by eddie-knight**
This resolves #41

### CODE REVIEW

**Comment by luigigubello** [comment]
Is the file empty?

Screenshot 2023-09-27 at 19 11 01

**Comment by eddie-knight** [comment]
Well this is awkward...

**Comment by scovetta** [comment]
This looks OK to me, but I've only dealt with Apache, adding @david-a-wheeler since I see this license in a bunch of other repos, just want to make sure OpenSSF is good with it.

**Comment by luigigubello** [comment]
We have the approval 🍹 thanks @david-a-wheeler

**Pull request merged**
