### PR TITLE
Governence docs

### PR DESCRIPTION
**Pull request by hythloda**
There have been some formalizations with governance for projects in the OpenSSF.

I think these are all for the better, but if you have a concern, PLEASE let me know soon! I plan to wait for 1 month (2024-04-14) before starting down this path of merging these unless there are concerns. 

The file that is most of interest and needs your review is the Scope.md. The rest of the files are standard spec files from the LF.

### CODE REVIEW

**Comment by luigigubello** [comment]
@hythloda For standard policies, why are not we using https://github.com/ossf/.github?

**Comment by hythloda** [comment]
Legal has said that it is standard for these docs to be in a governance folder rather than a .github folder.

**Comment by hythloda** [comment]
Any thoughts on this? Can we move it forward with the LF legal suggestion?

**Comment by eddie-knight** [comment]
Connected with Amanda via slack and we are comparing/contrasting this PR with #89

**Pull request closed without merging**
